# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='text',
            field=models.TextField(max_length=200, verbose_name='\u0442\u0435\u043a\u0441\u0442'),
        ),
    ]
