# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-02 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='header_text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='about',
            name='header_text_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=models.TextField(max_length=20000, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(max_length=20000, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='contact',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0430 \u043a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='contact',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u043a\u0430\u0440\u0442\u043e\u0447\u043a\u0430 \u043a\u043e\u043d\u0442\u0440\u0430\u0433\u0435\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='contact',
            name='header_text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='contact',
            name='header_text_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_en',
            field=models.TextField(max_length=20000, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_ru',
            field=models.TextField(max_length=20000, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='features',
            name='header_text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='features',
            name='header_text_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='features',
            name='subheader_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u043f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='features',
            name='subheader_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u043f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='options',
            name='header_text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='options',
            name='header_text_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='options',
            name='text_en',
            field=models.TextField(max_length=2000, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='options',
            name='text_ru',
            field=models.TextField(max_length=2000, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='slide',
            name='button_caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u043d\u0430\u0434\u043f\u0438\u0441\u044c \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='slide',
            name='button_caption_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u043d\u0430\u0434\u043f\u0438\u0441\u044c \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='slide',
            name='header_text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='slide',
            name='header_text_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='slide',
            name='material_text_en',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='slide',
            name='material_text_ru',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
