# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/about', verbose_name='\u0444\u043e\u0442\u043e'),
        ),
    ]
