# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20190602_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
