# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_contact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='button_cpation',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u043d\u0430\u0434\u043f\u0438\u0441\u044c \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
    ]
