# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='logos',
            name='is_vendor',
            field=models.BooleanField(default=True, verbose_name='\u0412\u0435\u043d\u0434\u043e\u0440?'),
            preserve_default=False,
        ),
    ]
