# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_logos_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430',
                'verbose_name_plural': '\u041d\u043e\u043c\u0435\u0440\u0430 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u043e\u0432',
            },
        ),
        migrations.AlterModelOptions(
            name='logos',
            options={'verbose_name': '\u041b\u043e\u0433\u043e\u0442\u0438\u043f', 'verbose_name_plural': '\u041b\u043e\u0433\u043e\u0442\u0438\u043f\u044b'},
        ),
    ]
