# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20190424_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='button_cpation',
            new_name='button_caption',
        ),
    ]
