# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20190424_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='text_position',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=6, verbose_name='\u043f\u043e\u0437\u0438\u0446\u0438\u044f \u0442\u0435\u043a\u0441\u0442\u0430'),
        ),
    ]
