# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20190424_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='text_position',
            field=models.CharField(choices=[('left', '\u0421\u043b\u0435\u0432\u0430'), ('center', '\u041f\u043e \u0446\u0435\u043d\u0442\u0440\u0443'), ('right', '\u0421\u043f\u0440\u0430\u0432\u0430')], default='left', max_length=1, verbose_name='\u043f\u043e\u0437\u0438\u0446\u0438\u044f \u0442\u0435\u043a\u0441\u0442\u0430'),
        ),
    ]
