# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_auto_20190424_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='logos',
            name='link',
            field=models.CharField(default='#', max_length=200, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442'),
            preserve_default=False,
        ),
    ]
