# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_logos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442'),
        ),
    ]
