# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_auto_20190424_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logos',
            new_name='Partners',
        ),
    ]
