# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 20:27
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_auto_20190424_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440', 'verbose_name_plural': '\u041f\u0430\u0440\u0442\u043d\u0435\u0440\u044b'},
        ),
        migrations.AddField(
            model_name='options',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='images/options', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
