# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 20:25
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_auto_20190425_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='header_text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='text_position',
            field=models.CharField(choices=[('left', '\u0421\u043b\u0435\u0432\u0430'), ('center', '\u041f\u043e \u0446\u0435\u043d\u0442\u0440\u0443'), ('right', '\u0421\u043f\u0440\u0430\u0432\u0430')], default='left', max_length=10, verbose_name='\u043f\u043e\u0437\u0438\u0446\u0438\u044f \u0442\u0435\u043a\u0441\u0442\u0430'),
        ),
    ]
