# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 20:55
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_auto_20190514_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='header_text'),
        ),
    ]
