# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 21:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_auto_20190514_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, default='', editable=False, populate_from='subheader_text'),
            preserve_default=False,
        ),
    ]
