# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 20:46
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_features_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='material_text',
            field=models.CharField(blank=True, max_length=20000, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, default='', editable=False, populate_from='header_text'),
            preserve_default=False,
        ),
    ]
